package view;

import Controller.VendasController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitarios.ConexaoBD;

/**
 * Classe responsável por gerar o relatório sintético de vendas
 * @author Rubens.lroliveira
 */
public class FrRelSintetico extends javax.swing.JFrame {

    /**
     * Creates new form frRelSintetico
     */
    ConexaoBD conecta = new ConexaoBD();

    private VendasController controller;

    public FrRelSintetico() {

        initComponents();

        try {
            preencherTabela();
        } catch (SQLException ex) {
            Logger.getLogger(FrRelSintetico.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        rdbData = new javax.swing.JRadioButton();
        rdbIdCliente = new javax.swing.JRadioButton();
        txtPesquisa = new javax.swing.JTextField();
        rdbPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRelatorio = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relatório Sintético");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pesquisar por:", 1, 0));

        buttonGroup1.add(rdbData);
        rdbData.setText("Data");

        buttonGroup1.add(rdbIdCliente);
        rdbIdCliente.setText("ID Cliente");

        rdbPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/loupe.png"))); // NOI18N
        rdbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbData)
                .addGap(18, 18, 18)
                .addComponent(rdbIdCliente)
                .addGap(18, 18, 18)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(rdbPesquisar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbData)
                    .addComponent(rdbIdCliente)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(rdbPesquisar)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tableRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID  Venda", "ID  Cliente", "Forma de Pgto.", "Total"
            }
        ));
        tableRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRelatorioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableRelatorio);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Método utilizado para retornar a página inicial do painel
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            FrInicio inicio = new FrInicio();
            inicio.setVisible(true);
            dispose();
            refreshTable();
        } catch (SQLException ex) {
            Logger.getLogger(FrRelSintetico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Método utilizado para retornar os dados de compra do cliente ao clicar em uma venda
     * @param evt 
     */
    private void tableRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRelatorioMouseClicked
        try {
            int idVenda = (int) tableRelatorio.getValueAt(tableRelatorio.getSelectedRow(), 0);
            String frmPgto = (String) tableRelatorio.getValueAt(tableRelatorio.getSelectedRow(), 2);
            conecta.conectar();
            conecta.executaSQL("SELECT count(*) as qtde FROM vendas_produtos where id_venda = " + idVenda);
            conecta.rs.first();
            int qtde = conecta.rs.getInt("qtde");
            String produtos = "";
            String msg = "";
            conecta.executaSQL("SELECT vendas.id as id_venda, clientes.nome as cliente, cpf, "
                    + "produtos.nome as produtos, vlr_venda as valor_produto, qtd_vendida, vendas.total, "
                    + "data_compra, hora FROM vendas INNER JOIN clientes on id_cli = clientes.id INNER JOIN "
                    + "vendas_produtos on vendas.id = id_venda INNER JOIN produtos on id_produto = produtos.id WHERE vendas.id = " + idVenda);

            int i = 1;
            while (conecta.rs.next()) {

                produtos += conecta.rs.getString("produtos") + "      ";
                produtos += "Qtde: " + conecta.rs.getInt("qtd_vendida") + "      ";
                produtos += "Valor: " + conecta.rs.getDouble("valor_produto") + "\n";

                if (i == qtde) {
                    msg = "ID da Venda: " + idVenda + "    Data: " + conecta.rs.getDate("data_compra")
                            + "     Horário: " + conecta.rs.getTime("hora") + "\n\nCliente: " + conecta.rs.getString("cliente")
                            + "     CPF: " + conecta.rs.getString("cpf") + "\n\nProdutos Vendidos: \n\n" + produtos + "\n Forma de Pagamento: "
                            + frmPgto + "\n\nTotal: R$" + conecta.rs.getDouble("total");

                }
                i++;

            }

            JOptionPane.showMessageDialog(rootPane, msg, "Relatório Analítico", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(FrRelSintetico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tableRelatorioMouseClicked

    /**
     * Método utilizado para realizar a pesquisa de vendas por data ou ID de cliente
     * @param evt 
     */
    private void rdbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbPesquisarActionPerformed
        // TODO add your handling code here:
        try {
            DefaultTableModel modelo = (DefaultTableModel) tableRelatorio.getModel();
            modelo.setNumRows(0);

            if (rdbData.isSelected()) {
                conecta.conectar();
                conecta.executaSQL("SELECT * FROM vendas WHERE data_compra = '" + txtPesquisa.getText() + "'");
                while (conecta.rs.next()) {
                    modelo.addRow(new Object[]{
                        conecta.rs.getInt("id"),
                        conecta.rs.getInt("id_cli"),
                        conecta.rs.getString("frm_pgto"),
                        conecta.rs.getDouble("total")

                    });
                }

            } else if (rdbIdCliente.isSelected()) {

                conecta.conectar();
                conecta.executaSQL("SELECT * FROM vendas WHERE id_cli = " + txtPesquisa.getText());
                while (conecta.rs.next()) {
                    modelo.addRow(new Object[]{
                        conecta.rs.getInt("id"),
                        conecta.rs.getInt("id_cli"),
                        conecta.rs.getString("frm_pgto"),
                        conecta.rs.getDouble("total")

                    });
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Favor selecionar uma opção de pesquisa.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrRelSintetico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rdbPesquisarActionPerformed

    /**
     * Método utilizado para preencher a tabela de vendas
     * @throws SQLException - tratamento de exceção
     */
    public void preencherTabela() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tableRelatorio.getModel();
        modelo.setNumRows(0);
        conecta.conectar();
        conecta.executaSQL("SELECT * FROM vendas");
        while (conecta.rs.next()) {
            modelo.addRow(new Object[]{
                conecta.rs.getInt("id"),
                conecta.rs.getInt("id_cli"),
                conecta.rs.getString("frm_pgto"),
                conecta.rs.getDouble("total")

            });
        }
    }
    
    /**
     * Método para atualizar a tabela de vendas
     */
    public void refreshTable() {
        tableRelatorio.invalidate();
        tableRelatorio.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrRelSintetico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrRelSintetico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrRelSintetico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrRelSintetico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrRelSintetico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbData;
    private javax.swing.JRadioButton rdbIdCliente;
    private javax.swing.JButton rdbPesquisar;
    private javax.swing.JTable tableRelatorio;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
